# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rob Lisy
title: Data Science and Business Intelligence
email: roblisy@gmail.com
website: www.github.com/roblisy/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  roblisy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rob-lisy-a4a9008
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Lisy_94.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Rob 
  
  I've been working in the data science / analytics / business intelligence space for over a decade, in industries like healthcare, SaaS, retail, manufacturing, and finance. I currently work with the Google Domains team to make buying domains a better experience.

#  I am most skilled in: 
#    <mark>thing A</mark>
#    <mark>thing B</mark>

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Google
        link: domains.google.com
        link_text: domains.google.com
        sub_title: Business System Analyst
        caption: May 2021 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Leading the curation and adoption of data science, metrics, and reporting for Google Domains.
      - layout: left
        title: Moz 
        link: moz.com
        link_text: moz.com
        sub_title: Manager, Business Intelligence
        caption: June 2019 - May 2020
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Managed team of analysts and data science to help improve marketing, product, finance, and customer service at Moz.
      - layout: left
        title: Nordstrom
        link: nordstrom.com
        link_text: nordstrom.com
        sub_title: Data Scientist
        caption:  March 2017 - May 2019
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Focused on problems of attribution, measurement, and marketing efficacy.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Washington Professional & Continuing Education
        caption: 2020
        sub_title: Certificate, Data Science
        
      - layout: left
        title: Case Western Reserve University, Weatherhead School of Management
        caption: 2007 - 2008
        sub_title: Managment of Information Science
        description: | # this will include new lines to allow paragraphs
          President of the IT club.
      
      - layout: left
        title: Denison University
        caption: 2000 - 2004
        sub_title: English Literature
        description: | # this will include new lines to allow paragraphs
          3x NCAA All-American swimmer

  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
